logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/location_db?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  servlet:
    context-path: /location
  port: 9090
